version: "3.8"

services:

  jinja2-live-render:
    container_name: jinja2-live-render
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - app-variables.env
    ports:
      - "8000:80"
    healthcheck:
      test: curl -f http://localhost/api/v1/health
      interval: 30s
      timeout: 10s
      retries: 2
      start_period: 5m